name: mess_server

services:

  app:
    build: 
      context: .
      dockerfile: app_dockerfile
    ports:
      - "7000:80"

  load_balancer:
    build: 
      context: .
      dockerfile: nginx_dockerfile
    ports:
      - "7001:80"

  kailash_server:
    build: 
      context: .
      dockerfile: kailash_dockerfile

  mm_server:
    build: 
      context: .
      dockerfile: mm_dockerfile
  
  sabari_server:
    build: 
      context: .
      dockerfile: sabari_dockerfile

  

